doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            cart_id: App\Infrastructure\Persistence\Doctrine\Type\CartIdType
            user_id: App\Infrastructure\Persistence\Doctrine\Type\UserIdType
            cart_item_id: App\Infrastructure\Persistence\Doctrine\Type\CartItemIdType
            product_id: App\Infrastructure\Persistence\Doctrine\Type\ProductIdType
            product_name: App\Infrastructure\Persistence\Doctrine\Type\ProductNameType
            money: App\Infrastructure\Persistence\Doctrine\Type\MoneyType
            quantity: App\Infrastructure\Persistence\Doctrine\Type\QuantityType
            order_id: App\Infrastructure\Persistence\Doctrine\Type\OrderIdType
            order_item_id: App\Infrastructure\Persistence\Doctrine\Type\OrderItemIdType
            order_status: App\Infrastructure\Persistence\Doctrine\Type\OrderStatusType
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            CartAggregate:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping/Cart/Aggregate'
                prefix: 'App\Domain\Cart\Aggregate'
                alias: CartAggregate
            CartEntity:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping/Cart/Entity'
                prefix: 'App\Domain\Cart\Entity'
                alias: CartEntity
            CheckoutAggregate:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping/Checkout/Aggregate'
                prefix: 'App\Domain\Checkout\Aggregate'
                alias: CheckoutAggregate
            CheckoutEntity:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping/Checkout/Entity'
                prefix: 'App\Domain\Checkout\Entity'
                alias: CheckoutEntity
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
